services:
  - type: web
    name: focusflow-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: SKIP_CHECK
        value: "true"